name = "Hyde"
license = "MIT"
licenselink = "https://github.com/andrewwbutler/hyde-lab-notebook/blob/master/LICENSE.md"
description = "Lab notebook theme based on hyde"
tags = ["notebook"]
features = ["blog", "themes"]
min_version = 0.21

[author]
    name = "andrewwbutler"
    repo = "https://www.github.com/andrewwbutler/hyde-lab-notebook"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
