theme = "hyde-lab-notebook"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Lab Notebook"


## Site Settings
[params]
	author = "Andrew Butler"
	dateformat = "Jan 2, 2006"
[outputs]
  home = ["HTML", "RSS", "JSON"]
  
## Main Menu
[[menu.main]]
    name = "Archive"
    weight = 100
    identifier = "archive"
    url = "/archive/"
[[menu.main]]
    name = "Getting Started"
    identifier = "getting-started"
    weight = 200
	url = "/getting-started/"
[[menu.main]]
    name = "Search"
    identifier = "search"
    weight = 99999
    url = "/search/"